---
- name: sjekk port
  hosts: "127.0.0.1"
  connection: local
  tasks:
    - name: wait for winrm port 5985 to come up 
      local_action: wait_for
                host="{{ VCENTER_MILJO }}{{ VCENTER_GUEST_NAME }}.lab.local"
                port=5985
                state=started
    - name: venter tjue sekunder
      pause:
        seconds: 20

- name: Wait for system to become reachable over WinRM
    wait_for_connection:
      timeout: 900