---
- name: sjekk port
  hosts: "127.0.0.1"
  connection: local
  tasks:
    - name: wait for sql port 1433 to come up 
      local_action: wait_for
                host="{{ VCENTER_GUEST_NAME_2 }}.lab.local"
                port=1433
                state=started
                timeout=900
                
    - name: venter tjue sekunder
      pause:
        seconds: 20