---
- name: Install Windows Updates
  hosts: "127.0.0.1"
  connection: local
  tasks:
    - name: wait for winrm port 5985 to come up 
      local_action: wait_for
                host=WIN-17U3KGNNGA3
                port=5985
                state=started
    - name: venter tjue sekunder
      pause:
        seconds: 20