---
- name: sjekk port
  hosts: "{{ VCENTER_MILJO }}{{ VCENTER_GUEST_NAME }}.lab.local"
  connection: local
  tasks:
      - name: Wait for system to become reachable over WinRM
    wait_for_connection:
      timeout: 900