---
- name: Install Windows Updates
  hosts: "all"

  tasks:
  - name: wait for winrm port 5985 to come up 
    local_action: wait_for
                  port=5985
                  state=started
  - name: venter tjue sekunder
    pause:
      seconds: 20
  - name: Windows Update
    win_updates:
      category_names:
      - Application
      - CriticalUpdates
      - DefinitionUpdates
      - SecurityUpdates
      - Updates
      reboot: yes  
  - name: Shutdown
    win_command: shutdown /s /t 0