---
- name: Install Windows Updates
  hosts: "all"

  tasks:
  - name: Windows Update
    win_updates:
      category_names:
      - Application
      - CriticalUpdates
      - DefinitionUpdates
      - SecurityUpdates
      - Updates
      reboot: yes  
  - name: Shutdown
    win_command: shutdown /s /t 0